Update metadata endpoints response types
quality-match/hari-client pull request #1
Opened 2024-08-13 15:22 UTC by katia-qm

**Background**
Metadata creation endpoints have changed their response types from None.

**Changes**
- created response types for metadata endpoints
- updates parser to work with parametrized generics

2024-08-13 15:51 UTC, Dens49 commented on hari_client/client/client.py
> +                models.UpdateHistogramsResponse | models.CreateCropsResponse
our minimum python version is 3.9, but using the pipe symbol in the typehint isn't supported in python 3.9. Can you switch to using typing.Union?

2024-08-14 05:36 UTC, Dens49 requested changes
Only 2 change requests:
- minimum python version we support is 3.9, but using the pipe for a union typehint isn't supported in python 3.9. All the new models have to be updated
- can you explain the support of the union in the docstring of `_parse_response_model` along with its limitations? For example the limits on nesting

2024-08-14 09:47 UTC, Dens49 commented on hari_client/client/client.py
> +            list[models.UpdateHistogramsResponse, models.CreateCropsResponse]: list of updated histograms and created crops
```suggestion
            list[typing.Union[models.UpdateHistogramsResponse, models.CreateCropsResponse]]: list of updated histograms and created crops
```

2024-08-14 10:07 UTC, katia-qm commented on hari_client/client/client.py
> +            list[models.UpdateHistogramsResponse, models.CreateCropsResponse]: list of updated histograms and created crops
oops, thanks for finding this!

2024-08-14 10:23 UTC, Dens49 approved these changes
looks good! just a tiny update for one of the docstrings

2024-08-14 12:32 UTC, merged