add attribute upload
quality-match/hari-client pull request #17
Opened 2024-09-30 14:44 UTC by mylius

This adds the ability to upload attributes to the HARI client.

Additional changes:
- some linting

2024-10-01 08:28 UTC, katia-qm requested changes
Thanks a lot for all the clean ups you did!

Looks good to me overall, have small comments and questions

Would have been nice if you separate linter clean ups commit next time please:)

2024-10-01 14:02 UTC, katia-qm commented on hari_client/models/models.py
> +    range: typing.Any | None = None
Just mirroring the api, I see

2024-10-01 14:03 UTC, katia-qm commented on hari_client/models/models.py
> +    sum: typeT | None = None
Just mirroring the api, I see

2024-10-01 14:03 UTC, katia-qm commented on hari_client/models/models.py
> +    range: typing.Any | None = None
Just mirroring the api as well, but still confusing to me

2024-10-02 06:12 UTC, mylius commented on hari_client/models/models.py
> +    sum: typeT | None = None
We want to guarantee, that the type is consistent for these fields, but now perscribe a specific type for them.

2024-10-02 06:13 UTC, mylius commented on hari_client/models/models.py
> +    model_config = pydantic.ConfigDict(validate_assignment=True, extra="forbid")
I will change it for the sake of consistency, but I believe in a lot of cases the API will reject them.

2024-10-02 06:25 UTC, mylius commented on hari_client/models/models.py
> +    range: typing.Any | None = None
Just mirroring the qm-mongodb model here, but I think the range would be provided as a tuple or list of typeT.

Looking closer at this: QM-Brain doesn't return the range as an interval, but rather just the distance between the the boundaries, but I guess Philip wasn't sure about that.

2024-10-02 07:08 UTC, katia-qm commented on hari_client/models/models.py
> +    model_config = pydantic.ConfigDict(validate_assignment=True, extra="forbid")
Ahh I see, we did it for the case if API returns something unexpected, not the other way round

2024-10-02 08:04 UTC, katia-qm commented
One more thing: inspect upload result part of quickstart is missing attributes as well:
https://github.com/quality-match/hari-client/blob/142629dd46704e56a0c99c9d9a99a52c59a14126/docs/example_code/quickstart.py#L107-L107

2024-10-02 08:14 UTC, katia-qm commented on hari_client/upload/hari_uploader.py
> +                return
could we return even before `filtered_upload_response` is calculated?

2024-10-02 14:21 UTC, mylius commented on hari_client/upload/hari_uploader.py
> +                return
Good point, and it should be a continue instead of a return i think!

2024-10-07 07:09 UTC, katia-qm requested changes
I have some change requests here.

Also please take a look at the unresolved conversations left

2024-10-07 07:09 UTC, katia-qm commented on docs/example_code/quickstart.py
> +print(f"attribute upload summary\n  {upload_results.attribute_objects.summary}")
attribute_objects? they don't exist :)
```suggestion
print(f"attribute upload status: {upload_results.attributes.status.value}")
print(f"attribute upload summary\n  {upload_results.attributes.summary}")
```

2024-10-08 08:57 UTC, katia-qm approved these changes
Great job!

2024-10-08 11:39 UTC, katia-qm commented on docs/example_code/quickstart.py
> +    print(f"attribute upload status: {upload_results.attributes.status.value}")
```suggestion
    print(f"attribute upload details: {upload_results.attributes.results}")
```

2024-10-08 11:57 UTC, merged