CRUD methods for attributes
quality-match/hari-client pull request #18
Opened 2024-10-01 07:46 UTC by mylius

Adds CRUD methods for attributes to the client.

2024-10-01 13:59 UTC, katia-qm requested changes
Create a separate attribute is missing (not bulk).
What about attribute values/metadata? I'm not sure whether they are needed or not

Comparing all the fields is very overwhelming, so I have to trust you here;)
Did you test all of the methods, to make sure everything works and the parsing doesn't break?

2024-10-01 13:59 UTC, katia-qm commented on hari_client/client/client.py
> +            success_response_item_model=models.Attribute,
Why does `get_attribute` return `model.Attribute`, but `get_attributeS` returns `list[models.AttributeResponse]`?

2024-10-02 15:22 UTC, mylius commented on hari_client/client/client.py
> +            success_response_item_model=models.Attribute,
Oversight on my part.

2024-10-02 15:24 UTC, mylius commented
> Create a separate attribute is missing (not bulk). What about attribute values/metadata? I'm not sure whether they are needed or not

Having people deal with values and metadata is probably a bit overwhelming, which is why we created the attribute endpoints, which wrap both of those.

> Comparing all the fields is very overwhelming, so I have to trust you here;) Did you test all of the methods, to make sure everything works and the parsing doesn't break?

I did do all CRUD operations at least once for one Attribute, but I didn't populate all fields and try all variations.

2024-10-07 19:40 UTC, katia-qm requested changes

2024-10-07 19:40 UTC, katia-qm commented on hari_client/client/client.py
> +        ml_predidictions: dict[str, float] | None = None,
ml_predi_di_ctions :) also in docstring

2024-10-07 19:40 UTC, katia-qm commented on hari_client/client/client.py
> +        annotatable_id: str | None = None,
annotatable id seems to be required on the api, could you please double-check?

2024-10-08 07:46 UTC, mylius commented on hari_client/models/models.py
> +    name: str
Not really, but I also don't think it is currently actively used.

2024-10-08 08:55 UTC, katia-qm approved these changes
Amazing, thanks a lot!

2024-10-08 12:02 UTC, merged