Support Media and MediaObject bulk creation endpoints
quality-match/hari-client pull request #2
Opened 2024-08-14 07:38 UTC by Dens49

Adds support for the media and media object bulk creation endpoints.

2024-08-15 12:31 UTC, katia-qm requested changes
Looks good, but I have some questions and nitpicks.

It was only 2 modified endpoints: for creating medias and media objects, right?

Will continue the review after debugging bulk methods

2024-08-15 12:31 UTC, katia-qm commented on hari_client/client/client.py
> +            dataset_id=dataset_id,
Let's rename the method to plural as we pass the batch size and can potentially create multiple urls. 
And by the way, why don't we have add_vis_to_mediaS and .._media_objectS methods? If we don't have the endpoints for that yet, there's no need to have a configurable batch_size in `get_presigned_visualisation_upload_url` function. Am I missing something?

2024-08-15 12:45 UTC, Dens49 commented on hari_client/client/client.py
> +                f"Expected batch_size to be in range 1 <= batch_size <= {HARIClient.BULK_UPLOAD_LIMIT}, but received: {batch_size}."
yeah I also don't like the _pack method, but it came with the prototype and we didn't refactor that before the first release, because it already worked

2024-08-15 13:36 UTC, Dens49 commented on hari_client/client/client.py
> +        media_object_dicts = [media_object.dict() for media_object in media_objects]
I think it will be removed in a future update, but for now we want to keep it and follow the backend

2024-08-15 13:38 UTC, Dens49 commented on hari_client/client/client.py
> +        visualisation_config_id: typing.Optional[str] = None,
good catch, missed this in the refactor

2024-08-15 14:02 UTC, Dens49 commented on hari_client/client/client.py
> +            dataset_id=dataset_id,
>why don't we have add_vis_to_mediaS and .._media_objectS methods

with the endpoints, you can only add a single visualisation to a single media or media object.

>If we don't have the endpoints for that yet, there's no need to have a configurable batch_size in get_presigned_visualisation_upload_url function

The hari-client is a very thin wrapper library and these methods follow the hari api closely. The endpoint for getting a presigned visualisation upload url in hari supports specifying a batch_size, so our wrapper method has to support that, too, even though our internal function doesn't make use of that. That way a user could still use that function and generate visualisation upload urls for themselves, even though that's unlikely.

2024-08-15 14:06 UTC, Dens49 commented on hari_client/models/models.py
> +class SuccessSummary(pydantic.BaseModel):
seems overkill to me. That would need us to assume they're always gonna be used in that context only

2024-08-15 14:08 UTC, Dens49 commented on hari_client/client/client.py
> +        presign_response = self.get_presigned_media_upload_url(
I'd rather stick to following the hari api and its naming choices closely. Also even if we renamed the method to be pluralized, there would still only be one response from the call

2024-08-15 14:19 UTC, Dens49 commented on hari_client/client/client.py
> +                f"Expected batch_size to be in range 1 <= batch_size <= {HARIClient.BULK_UPLOAD_LIMIT}, but received: {batch_size}."
oh lol I thought I already did that. There's the `BulkUploadLimitExceededError` exception, but I missed adding it here

2024-08-16 05:37 UTC, katia-qm commented on hari_client/models/models.py
> +class SuccessSummary(pydantic.BaseModel):
They seem to be used only for bulk requests though, otherwise why would you need a summary for a single request? Maybe at least as an addition to the docstring `Quantifies how many items were successfully uploaded and how many failed **_in a bulk request_**`

2024-08-16 05:51 UTC, Dens49 commented on hari_client/client/client.py
> +                f"Expected batch_size to be in range 1 <= batch_size <= {HARIClient.BULK_UPLOAD_LIMIT}, but received: {batch_size}."
I've added a new `ParameterRangeError` exception class to be used in the two presigned url endpoint methods.
The exception in create_medias and create_media_objects methods is renamed to `BulkUploadSizeRangeError` now.

2024-08-16 06:07 UTC, katia-qm commented on hari_client/client/client.py
> +        media_object_dicts = [media_object.dict() for media_object in media_objects]
Still a question whether we should do the manipulations with qm_data and reference_data in create_media_objects method as well

2024-08-16 06:11 UTC, katia-qm approved these changes
Nice! Just one nitpick.

There are still some open questions from previous review

And tests for ParameterRangeError are missing, seems necessary for getting limited number of presigned urls

2024-08-16 06:11 UTC, katia-qm commented on hari_client/client/errors.py
> +            f"The valid range for the {param_name} parameter is: {minimum=}, {maximum=}, but found {found_amount} items"
Nit: would rather call it found_value instead of amount, it's a batch size value

2024-08-16 06:19 UTC, Dens49 commented on hari_client/client/client.py
> +        media_object_dicts = [media_object.dict() for media_object in media_objects]
no, that's not necessary.
https://github.com/quality-match/hari-client/blob/f9695cd1884d1074e149687a1988d25cccad6705/hari_client/client/client.py#L1125-L1126
When you call the `*.dict()` method on the pydantic model object, then all its contents are already transformed to python native data types. The `create_media_object` method just has a flat list of arguments, so both had to be transformed separately.

2024-08-16 06:23 UTC, Dens49 commented on hari_client/models/models.py
> +class SuccessSummary(pydantic.BaseModel):
Ok the SuccessSummary class seems super generic by its name, but its doc string pins it to being used for the bulk uploads. I'll rename it, makes sense

2024-08-16 06:24 UTC, katia-qm commented on hari_client/client/client.py
> +        media_object_dicts = [media_object.dict() for media_object in media_objects]
Ah okay, thanks for the explanation! So it will be up to the user to transform to MediaObjectCreate :+1:

2024-08-16 06:41 UTC, merged