Add force_recreate flag
quality-match/hari-client pull request #39
Opened 2024-11-08 10:14 UTC by mylius

Adds a flag for metadata rebuidling, crop and thumbnail creation, that forces the recreation of existing thumbnails and crops. This flag is only available to internal users.

2024-11-08 12:55 UTC, alvarotroya approved these changes
Lgtm 👍 thx for the quick fix!

2024-11-08 13:31 UTC, katia-qm requested changes
Maybe you could also then add a comment to the endpoints that are not available to externals?

2024-11-08 13:31 UTC, katia-qm commented on hari_client/client/client.py
> +            force_recreate: If True already existing crops and thumbnails will be rereated only available for certain user roles
```suggestion
            force_recreate: If True already existing crops and thumbnails will be recreated; only available for certain user roles
```

2024-11-11 11:03 UTC, katia-qm approved these changes

2024-11-11 11:03 UTC, katia-qm commented on hari_client/client/client.py
> +            force_recreate: If True already existing crops and thumbnails will be rereated only available for certain user roles
```suggestion
            force_recreate: If True already existing crops and thumbnails will be recreated; only available for certain user roles
```

2024-11-11 11:03 UTC, katia-qm commented on hari_client/client/client.py
> +            force_recreate: If True already existing crops and thumbnails will be rereated only available for certain user roles
maybe only available to qm internal users only?

2024-11-11 11:03 UTC, katia-qm commented on hari_client/client/client.py
> +            force_recreate: If True already existing crops and thumbnails will be recreated; only available for certain user roles
maybe only available to qm internal users only?

2024-11-11 12:40 UTC, katia-qm approved these changes

2024-11-11 12:40 UTC, katia-qm commented on hari_client/client/client.py
> +            force_recreate: If True already existing crops and thumbnails will be rereated only available for qm internal users
sorry:)
```suggestion
            force_recreate: If True already existing crops and thumbnails will be recreated only available for qm internal users
```

2024-11-11 13:17 UTC, mylius commented on hari_client/client/client.py
> +            force_recreate: If True already existing crops and thumbnails will be receated only available for qm internal users
Sorry :/

2024-11-11 14:28 UTC, katia-qm approved these changes
Thanks!

2024-11-11 14:38 UTC, merged