New example script: add new data to an existing dataset
quality-match/hari-client pull request #41
Opened 2024-11-15 13:43 UTC by Dens49

Added an example script that demonstrates what needs to be done in order to upload new media and media objects to an existing dataset.
It's a demonstration for how to achieve that with the hari-client, not a ready to use utility.
Many of these details could be handled directly in the hari_uploader utility or in the HARI backend.

2024-11-18 08:30 UTC, katia-qm requested changes
Looks really great! Do you consider adding in to the documentation rather then here? Just leave the script with the comments here same like for the quickstart?

2024-11-18 09:18 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/README.md
> +  - by reusing the existing attribute ids and attribute types
Because the backend expects you to have set that correctly.

2024-11-18 09:25 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +media_attribute_id_lookup["new_media_attribute"] = uuid.uuid4()
I agree it's not necessary in this example, but I want the example to emphasize attribute id reuse.
If I think about how I'd build a proper script for my use case from this example code, I'd have to build some lookup for new attribute ids anyway when I want to reuse them, if media_attribute_id_lookup wasn't there

2024-11-18 09:28 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +]
because the backend expects that. HariUploader also does this with the object category subsets which are media object subsets. Otherwise HARI won't include those medias in the medias count for the media object subsets.

2024-11-18 09:32 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +# 3. Set existing subset_id on the new media and media object
What's actually happening at the lower level in code is that you append a subset_id to the list of subset_ids of medias and media_objects.
The higher level outcome of this is that you've added the medias and media_objects to that subset. I'd rather have the comments that are close to the code explain the actual code. I'll add an explanation of this difference to the readme

2024-11-18 09:32 UTC, katia-qm commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +new_media.add_media_object(new_media_object)
are you sure? hari uploader takes media object attributes from media objects, and if at the moment of adding object to media it doesn't have attributes, why does the uploader get them from?

2024-11-22 10:22 UTC, Emprime approved these changes
I like the script, my only issue is a general concern about this and the example script. It is very unrealistic that I want to upload one image. I would prefer a script which does this e.g. based on complete folders. 
I ran into multiple issues when using the quickstart guide e.g. breaking uploads, missing entries and so on because it was tested with larger (more realistic) data amounts.

2024-11-22 10:22 UTC, Emprime commented on docs/example_code/upload_new_data_to_existing_dataset/README.md
> +> :warning: <b>Disclaimer: In most cases it makes more sense to upload your data as a new dataset - especially when you've already done a lot of work with that dataset through annotation runs</b>
I would not add this, My upload crashed regularly and thus I need this functionality.

2024-11-22 10:22 UTC, Emprime commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +if len(duplicate_medias) > 0:
I'm not sure if this is a good solution, I normally want to upload data even if there are duplicates. The upload should not completely be blocked but just the duplicates be removed.

2024-11-27 08:43 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +if len(duplicate_medias) > 0:
I agree. Let's have the behavior you suggested when we add generic utility script for this use case

2024-11-27 08:57 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +media_attribute_id_lookup["new_media_attribute"] = uuid.uuid4()
looked at this with a fresh brain really helped. I understand and agree now :+1:

2024-11-27 09:50 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
> +new_media.add_media_object(new_media_object)
I think we discussed this offline last week. Will mark as resolved, but reach out if you want to discuss this more

2024-11-27 09:59 UTC, Dens49 commented on docs/example_code/upload_new_data_to_existing_dataset/README.md
> +> :warning: <b>Disclaimer: In most cases it makes more sense to upload your data as a new dataset - especially when you've already done a lot of work with that dataset through annotation runs</b>
makes sense - I've rephrased the case where it doesn't make too much sense. Hope it's clearer now.

2024-11-27 13:10 UTC, katia-qm approved these changes
Amazing! Thanks a lot for the changes:) 
Will it also go to the docs website in the end?

2024-11-27 13:10 UTC, katia-qm commented on docs/example_code/upload_new_data_to_existing_dataset/README.md
> +> :warning: <b>Disclaimer: In the case that you've already did a lot of work with your dataset with annotation runs, we recommend that you create a new dataset and upload your new data there in order
```suggestion
> :warning: <b>Disclaimer: In the case that you've already used your dataset for annotation runs, we recommend that you create a new dataset and upload your new data there in order to keep a better overview.</b>
```

2024-11-27 13:39 UTC, merged