Fix query arg serialization
quality-match/hari-client pull request #49
Opened 2024-12-04 09:29 UTC by Dens49

1721653103

The `query` argument wasn't serialized properly for multiple methods.
This is now fixed. Support for existing workarounds, where the query argument was passed as an already stringified single QueryParameter oder LogicParameter object or as a list of those is kept, but will be removed in the future. If you've already used this workaround, please update your scripts.

2024-12-04 11:37 UTC, katia-qm requested changes
Good job! I got small remarks and questions as always:)

I noticed that get_vis_config endpoint doesn't have all the arguments that the corresponding api method has, is there any reason for it? If not, can you add the missing arguments? (query arg is among the missed ones)

2024-12-04 11:37 UTC, katia-qm commented on tests/test_client.py
> +    "query, expected",
nitpick: could you also add query=None test case please?

2024-12-04 11:37 UTC, katia-qm commented on hari_client/client/client.py
> +
do you think there is a way to move this somewhere in the _request and check if query is in params?

2024-12-04 11:37 UTC, katia-qm commented on hari_client/client/client.py
> +                log.warning(msg)
why two warnings, what is the difference?

2024-12-04 11:37 UTC, katia-qm commented on hari_client/client/client.py
> +            elif isinstance(x, str):
the user can pass here any string, if so, we get an error on the api. We should just let it be, right?

2024-12-04 11:37 UTC, katia-qm commented on hari_client/client/client.py
> +            elif isinstance(x, str):
btw we should probably improve the error message there

2024-12-04 11:37 UTC, katia-qm commented on hari_client/client/client.py
> +    """
maybe
```suggestion
    """Serialize query list to a list of strings that can be used as a QueryList parameter in the HARIClient::_request method. 
    You can pass QueryList, as well as a single already serialized QueryParameter and LogicParameter object (serialized with json.dumps), or a list of them.
    Note that in the future only QueryList will be supported, for now other types are supported due to existing workarounds.

    Args:
        query: The QueryList to serialize
    """
```

2024-12-04 11:37 UTC, katia-qm commented on hari_client/client/client.py
> +        log.warning(msg)
maybe we should add an else there? Otherwise we get 500 error with empty message for unsupported types

2024-12-04 13:40 UTC, Dens49 commented on hari_client/client/client.py
> +
thought about that, too, but I'd rather have this responsibility explicitly in the method that knows that it has such a query param. `_request` shouldn't be concerned with such specifics imo.

2024-12-04 13:46 UTC, Dens49 commented on hari_client/client/client.py
> +                log.warning(msg)
the first is a native python warning and the other is just logging the message with the "warning" log level. Depending on the configured log level, the warning might not be logged. I couldn't a definitive answer on whether one should be preferred over the other. Using both doesn't hurt and for example has the effect that in successful pytest runs you still see the warnings, even though logs are not printed for successful runs.

2024-12-04 13:48 UTC, Dens49 commented on hari_client/client/client.py
> +        log.warning(msg)
I'd leave handling unsupported types to the requests module, as it was doing before

2024-12-04 13:56 UTC, Dens49 commented on hari_client/client/client.py
> +            elif isinstance(x, str):
> the user can pass here any string, if so, we get an error on the api. We should just let it be, right?

agreed, the backend will complain if it's not a proper QueryParameter or LogicParameter. Since it's not intended behavior anyway, I wouldn't do extra validation here.

> btw we should probably improve the error message there

which error message where?

2024-12-04 14:09 UTC, Dens49 commented on hari_client/client/client.py
> +    """
The type naming leads to confusion here. I'll reiterate in the docstring.
The type of the `query` arg is `QueryList` which is a `list` of `QueryParameter` objects (and or LogicParameter). The method serializes a variable of type `QueryList` to a list of strings which the `HARIClient::_request` method can translate into `HTTP query parameters`, which the backend can parse as a `QueryList` again.

2024-12-04 14:41 UTC, katia-qm commented on hari_client/client/client.py
> +
Yeah, makes sense. Just hope it will not get forgotten for new endpoints

2024-12-04 14:46 UTC, katia-qm commented on hari_client/client/client.py
> +                log.warning(msg)
hmm and none of them is printed 100% of time?

2024-12-04 14:55 UTC, Dens49 commented on hari_client/client/client.py
> +
> Just hope it will not get forgotten for new endpoints

ouch, that's a really good point. Let me have another look...

2024-12-04 15:04 UTC, katia-qm commented on hari_client/client/client.py
> +                log.warning(msg)
Isn't using warnings sufficient for all the cases then? I don't really mind having both, but may be confusing for the users that get 2 same warnings (as for me)

2024-12-05 12:52 UTC, Dens49 commented on hari_client/client/client.py
> +                log.warning(msg)
as long as the user doesn't redirect stderr, the warnings will surface. Only kept warnings.warn now

2024-12-05 13:07 UTC, katia-qm commented on hari_client/client/client.py
> +            elif isinstance(x, str):
maybe you could also add it to the error improvement ticket you created?

2024-12-05 15:06 UTC, katia-qm approved these changes
Good job!

2024-12-06 11:22 UTC, Dens49 commented on hari_client/client/client.py
> +    """Prepares query parameters for the request modules `request` method.
oh there's an apostrophe missing. `... for the request module's "request" method.`

2024-12-10 09:51 UTC, merged