add validations for initial attributes
quality-match/hari-client pull request #55
Opened 2024-12-12 13:30 UTC by Dens49

the validation is run automatically when using the hari_uploader's upload method.
Per default the validation is also run in the client's create_attributes method, but can be disabled with an arg, which the hari_uploader uses to prevent validation from running again for every batch.
Also took the opportunity to set the annotatable_type of attributes in the hari_uploader before the upload happens. Knowing the annotatable type is important for the validation.

2024-12-12 14:56 UTC, katia-qm requested changes
Good job! I left come comments about missing validations.

The biggest concern I have is that we take name instead of id as a source of truth that goes against api implementation (and the docs), but we can discuss it

2024-12-12 14:56 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +def validate_initial_attributes(
All the validations you added are common between all types of attributes, so we could rename it to just `validate_attributes`

2024-12-12 14:56 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +        - have the same id
I totally get the reasoning here, but I'm still not sure whether we could put it as a fact.
In the docs for attributes we say that `attribute with the same **id** and annotatable type must be consistent`, so it's a contradiction

2024-12-12 14:56 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +                if name_value_type_map[attribute.name] != value_type:
None is a valid value, go it can get mixed with other types. However i'm not sure if none is a valid value for initial attributes. Maybe we should add another validation here, but it's not there in the api. Anyway the validation function is general for all attributes now

2024-12-12 14:56 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +                    )
we should also check that types of list elements are the same as list we compare to

2024-12-12 14:56 UTC, katia-qm commented on hari_client/client/errors.py
> +            + " Make sure every attribute with the same name and attribute type has the same value type."
```suggestion
            + " Make sure every attribute with the same name and annotatable type has the same value type."
```

2024-12-12 14:57 UTC, katia-qm commented on hari_client/client/errors.py
> +            + " Make sure every attribute with the same name and attribute type has the same value type."
and everywhere else you find it

2024-12-12 16:12 UTC, Dens49 commented on hari_client/models/validation/attribute_validation.py
> +                if name_value_type_map[attribute.name] != value_type:
meaning it should be ok for `None` to be mixed in with anything?

2024-12-17 21:40 UTC, katia-qm submitted a review, later dismissed
Great job, thanks for the effort! I know these validations are quite overwhelming, but it's worth it for sure.

I think consistency validation for annotatable type/attribute group/attribute type is still missing

2024-12-17 21:40 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +    """Raises an error if any requirements for attributes aren't met.
```suggestion
    """Raises an error if any requirements for attributes consistency aren't met.
```

2024-12-17 21:40 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +      - contain only the same value type as other attributes with the same name and annotatable type
```suggestion
   - attributes with value type list must
      - have consistent element value types within the list
      - have consistent element value types across all values for the attributes with the same name and annotatable type
```

2024-12-17 21:40 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +      - The value `None` isn't taken into account when value type consistency is checked.
```suggestion
    Exceptions:
      - The value `None` isn't taken into account when value type consistency is checked.
      - Numeric types (int, float) could be mixed
```

2024-12-17 21:40 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +        AttributeValidationIdNotReusedError: If another attribute with the same name and attribute type has a different id.
```suggestion
        AttributeValidationInconsistentListElementValueTypesError: If the elements in a list attribute value have inconsistent value types.
        AttributeValidationInconsistentListElementValueTypesMultipleAttributesError: If multiple attributes with list value have inconsistent element value types.
        AttributeValidationIdNotReusedError: If multiple attributes with the same name and attribute type have different ids.
```

2024-12-17 21:40 UTC, katia-qm commented on hari_client/upload/hari_uploader.py
> +            AttributeValidationIdNotReusedError: If another attribute with the same name and attribute type has a different id.
Do we have to duplicate the exceptions here? Maybe it's enough to have them in the validation function

2024-12-17 21:40 UTC, katia-qm commented on hari_client/client/errors.py
> +        super().__init__(message)
Error messages seem a little bit confusing to me, but I also don't know how to rephrase it better.

The fact that we have to mention `with the same name and annotatable type` everywhere really kills me.

2024-12-17 21:40 UTC, katia-qm commented on hari_client/models/validation/attribute_validation.py
> +        name_value_type_map: dict[str, str] = {}
Would be really nice to make it a little bit more modular, at least separate validation for list and non-list values to a separate function if possible. If we later add more validations the function will grow and make become a mess

2024-12-17 21:40 UTC, katia-qm commented on tests/test_attribute_validations.py
> +def test_attribute_validation_inconsistent_value_type(attributes):
I didn't check all the tests yet, but maybe it would make sense to check the validation tests for the api to be sure we didn't forget any test cases

2024-12-18 12:54 UTC, Dens49 commented on hari_client/client/errors.py
> +        super().__init__(message)
Think about it that way: as a user you'll hopefully only see those messages very rarely and so you're probably happy to see enough detail to explain the problem and the expectations.

2024-12-18 12:55 UTC, Dens49 commented on hari_client/upload/hari_uploader.py
> +            AttributeValidationIdNotReusedError: If another attribute with the same name and attribute type has a different id.
yeah right, having them duplicated here doesn't seem to be helpful

2024-12-19 09:02 UTC, Dens49 commented
I did a refactor of the validation code, which surfaced two bugs :partying_face: (they're fixed, see latest two commits).
I also added a few more test cases and tried to improve the explanations in the doc strings

2024-12-19 15:26 UTC, FBOBecker approved these changes
Thanks for adding these. From what I can judge it is looking good. Just some questions here and there as I am not super familiar with the client (yet).

2024-12-19 15:26 UTC, FBOBecker commented on hari_client/models/validation/attribute_validation.py
> +            if self.name_id_map[attribute.name] != str(attribute.id):
hmm this is only an artifact because we actually use these merged Attribute Models for the client, right?
Technically, we store the name only once on the metadata, so kind of redundant here I assume.
Did we ever consider actually using the difference of attr metadata and value for the client?

2024-12-19 15:26 UTC, FBOBecker commented on hari_client/models/validation/attribute_validation.py
> +            if value_type != "NoneType":
you could probably remove that part as it would be checked within the method either way

2024-12-19 15:26 UTC, FBOBecker commented on hari_client/models/validation/attribute_validation.py
> +            ):
Sorry, too unfamiliar with the client but: Do we allow for different attributes to be uploaded? E.g., brightness and contrast at the same time?

2024-12-20 08:00 UTC, Dens49 commented on hari_client/models/validation/attribute_validation.py
> +    ) -> None:
I used to be camp "only typehint what's returned explicitly", but Alvaro taught me we actually have the convention to also typehint `-> None` if there's no explicit return.
This method has one explicit return, but no return value, so always returns None

2024-12-20 08:50 UTC, merged