Update example with status tracking
quality-match/hari-client pull request #6
Opened 2024-08-20 13:54 UTC by katia-qm

Update quickstart script with checking thumbnails creation status before triggering crops creation

2024-08-20 16:31 UTC, Dens49 requested changes
Is there a way to get the processing job status just from the trace_id, without having to find the thumbnails_job_id first?

2024-08-20 16:31 UTC, Dens49 commented on docs/example_code/quickstart.py
> +        (job.id for job in jobs if job.process_name == "create_thumbnails"), ""
where can you find the `job.process_name`?

2024-08-20 16:31 UTC, Dens49 commented on docs/example_code/quickstart.py
> +        (job.id for job in jobs if job.process_name == "create_thumbnails"), ""
is there a way to skip these lines and only use the trace_id to get the status?

2024-08-20 16:31 UTC, Dens49 commented on docs/example_code/quickstart.py
> +    while job_status != "success":
nitpick: is there an enum you can use for the status check?

2024-08-20 16:31 UTC, Dens49 commented on hari_client/client/client.py
> +    def trigger_thumbnails_creation(
nitpick: maybe even `_job` as a suffix for all of them? --> `trigger_thumbnails_creation_job`?

2024-08-21 05:04 UTC, katia-qm commented on docs/example_code/quickstart.py
> +        (job.id for job in jobs if job.process_name == "create_thumbnails"), ""
created a enum for it

2024-08-21 05:10 UTC, katia-qm commented on docs/example_code/quickstart.py
> +        (job.id for job in jobs if job.process_name == "create_thumbnails"), ""
Nope, for get processing job endpoint we could only filter by job_id.
We can filter by trace id in get processing jobS endpoint, and then we need find which of the jobs is for thumbnails creation

2024-08-21 05:40 UTC, katia-qm commented on docs/example_code/quickstart.py
> +        (job.id for job in jobs if job.process_name == "create_thumbnails"), ""
Nope, for `get processing job` endpoint we could only filter by job_id.
We can filter by trace id in `get processing jobS` endpoint and there is actually the job status for each job in the response, but in case if the status is not success, we will need to call this endpoint to retrieve all the jobs and loop over them to find the needed one again and again

2024-08-21 05:53 UTC, Dens49 commented on docs/example_code/quickstart.py
> +        (job.id for job in jobs if job.process_name == "create_thumbnails"), ""
ah ok thanks for the explanation :+1:

2024-08-21 05:55 UTC, Dens49 approved these changes
thanks!

2024-08-21 05:57 UTC, merged