Fix pre commit
quality-match/hari-client pull request #9
Opened 2024-08-22 22:14 UTC by Schmaexxi

Use mypy and flake8 for pre-commit hooks.

I had to invalidate mypy a bit because the [parse_response_model-method](https://github.com/quality-match/hari-client/blob/81a31c89b43d3251a3b89499e2ccc0cd9ff3a40d/hari_client/client/client.py#L19-L21) has too many return types, which have to be propagated throughout almost every method in the client.

I stopped after a while because there was no end in sight to make this conform with the type checker.
We should look at the return types of the parse_response_model-method and figure out a way to make this mypy-conform to give us type-safety.

2024-08-23 06:02 UTC, Dens49 requested changes
the PR contains a lot more changes than just updating the pre-commit hook configuration.
there also seem to be some merging problems which could be the cause of the mypy problems you saw.
please keep the typehints for the parsing logic as precise as possible. Let's discuss the mypy problems first.

2024-08-23 06:47 UTC, Schmaexxi commented on hari_client/client/client.py
> +                    return [(item, item_type) for item in response_data]
thanks for catching that - not sure which hook did that - I didn't touch that :D

2024-08-23 06:48 UTC, Schmaexxi commented on hari_client/client/client.py
> +    raise errors.ParseResponseModehandle_union_parsinglError(
hmm, I didn't merge anything 🤔 
will look into it, thanks

2024-08-23 06:51 UTC, Schmaexxi commented on hari_client/models/models.py
> +class BaseBulkItemResponse(pydantic.BaseModel):
Mypy told me that it doesn't make sense in a new class definition
It could be a configuration attribute the pydantic.BaseModel takes but it never should have worked as intended like this so I removed it
What was the intention of allowing arbitrary types (I should have asked that before)

2024-09-08 19:31 UTC, Schmaexxi commented on setup.py
> +        "dev": ["pre-commit", "types-requests"],
would just be stubs for mypy

2024-09-08 19:32 UTC, Schmaexxi commented on hari_client/client/client.py
> +) -> T | list[typing.Any] | dict[typing.Any, typing.Any] | typing.Any:
I agree with you, this was mostly to just get mypy working.
I took a different approach in https://github.com/quality-match/hari-client/pull/11

2024-09-08 19:34 UTC, Schmaexxi commented on hari_client/__init__.py
> +__all__ = ["HARIClient", "Config", "errors", "models", "hari_uploader"]
it would otherwise break.
It's only used for importing everything using the asterisk notation ([docs](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package))
Feel free to try it out

```python
from hari_client import *
```

2024-11-08 11:26 UTC, Schmaexxi commented
outdated

2024-11-08 11:26 UTC, closed without merging